const medicalAbbreviations = {
  medicineTiming: {
    OD: "Once daily",
    BD: "Twice daily",
    TDS: "Three times daily",
    QID: "Four times daily",
    HS: "At bedtime",
    SOS: "When needed",
    PRN: "As required",
    STAT: "Immediately",
    AC: "Before meals",
    PC: "After meals",
    OM: "Every morning",
    ON: "Every night",
  },

  dosagePatterns: {
    "1-0-0": "Morning only",
    "0-1-0": "Afternoon only",
    "0-0-1": "Night only",
    "1-0-1": "Morning and night",
    "1-1-0": "Morning and afternoon",
    "0-1-1": "Afternoon and night",
    "1-1-1": "Morning, afternoon, and night",
  },

  examination: {
    "B/L": "Bilateral (both sides)",
    AE: "Air Entry",
    "AE+": "Air entry present",
    "B/L AE+": "Air entry present in both lungs",
    WNL: "Within normal limits",
    NAD: "No abnormality detected",
    RS: "Respiratory System",
    CVS: "Cardiovascular System",
    CNS: "Central Nervous System",
    PA: "Per Abdomen",
    "P/A Soft": "Abdomen soft on examination",
    "F+": "Fever present",
    AF: "Afebrile (no fever)",
    Wheeze: "Whistling sound in lungs",
    Crepts: "Crackles heard in lungs",
    Congestion: "Mucus/inflammation in airways",
  },

  symptoms: {
    SOB: "Shortness of breath",
    URI: "Upper respiratory infection",
    URTI: "Upper respiratory tract infection",
    LRTI: "Lower respiratory tract infection",
    AR: "Allergic rhinitis",
    GE: "Gastroenteritis",
    NV: "Nausea and vomiting",
    DC: "Diarrhea / loose stools",
    CO: "Complains of",
  },

  investigations: {
    CBC: "Complete Blood Count",
    Hb: "Hemoglobin",
    TLC: "Total Leukocyte Count",
    DLC: "Differential Leukocyte Count",
    ESR: "Erythrocyte Sedimentation Rate",
    CRP: "C-Reactive Protein",
    RBS: "Random Blood Sugar",
    FBS: "Fasting Blood Sugar",
    PPBS: "Post-Prandial Blood Sugar",
    LFT: "Liver Function Test",
    KFT: "Kidney Function Test",
    CXR: "Chest X-Ray",
    ECG: "Electrocardiogram",
    USG: "Ultrasonography",
  },

  symbols: {
    "+": "Present / Positive",
    "-": "Absent / Negative",
    "↑": "Increased",
    "↓": "Decreased",
    x3d: "For 3 days",
    x5d: "For 5 days",
    x1w: "For 1 week",
  },
};

export default medicalAbbreviations;
